// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dewldowxkntgqhvmhggk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRld2xkb3d4a250Z3Fodm1oZ2drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODA2OTAsImV4cCI6MjA1ODU1NjY5MH0.n4zunVxyP3HAO8GR9KvsHwbqN4LwHcZlYEfLY5d3GTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);